version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: juans1910
      POSTGRES_DB: UsersDataBase
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

